// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestAPIEF.Data;

#nullable disable

namespace RestAPIEF.Migrations
{
    [DbContext(typeof(RestAPIDbContext))]
    [Migration("20260124162710_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RestAPIEF.Models.Interest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("Websitelink")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("Interests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Not the biggest fan of heights",
                            Name = "Hiking",
                            PersonId = 1,
                            Websitelink = "www.hiking.net"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Uses a variety of spices",
                            Name = "Cooking",
                            PersonId = 1,
                            Websitelink = "www.cooking.com"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Favorite genre are mystery novels",
                            Name = "Reading",
                            PersonId = 2,
                            Websitelink = "www.reading.com"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Travel to the alps this summer",
                            Name = "Traveling",
                            PersonId = 2,
                            Websitelink = "www.traveling.com"
                        },
                        new
                        {
                            Id = 5,
                            Description = "On the computer",
                            Name = "Gaming",
                            PersonId = 3,
                            Websitelink = "www.gaming.com"
                        });
                });

            modelBuilder.Entity("RestAPIEF.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Johan",
                            LastName = "Dag",
                            PhoneNumber = "123-456-7890"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Anna",
                            LastName = "Berg",
                            PhoneNumber = "987-654-3210"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Oscar",
                            LastName = "Chas",
                            PhoneNumber = "000-000-0123"
                        });
                });

            modelBuilder.Entity("RestAPIEF.Models.Interest", b =>
                {
                    b.HasOne("RestAPIEF.Models.Person", null)
                        .WithMany("interests")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RestAPIEF.Models.Person", b =>
                {
                    b.Navigation("interests");
                });
#pragma warning restore 612, 618
        }
    }
}
